import type { EntitySchema } from '@/types/schema';

export const contactSchema: EntitySchema = {
  name: 'contact',
  label: 'Contacto',
  pluralLabel: 'Contactos',
  icon: 'user',
  fields: [
    {
      name: 'nombres',
      label: 'Nombres',
      type: 'string',
      required: true,
      searchable: true,
      sortable: true,
    },
    {
      name: 'apellidos',
      label: 'Apellidos',
      type: 'string',
      required: true,
      searchable: true,
      sortable: true,
    },
    {
      name: 'nombreCompleto',
      label: 'Nombre Completo',
      type: 'string',
      required: true,
      searchable: true,
      sortable: true,
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      required: true,
      unique: true,
      searchable: true,
      filterable: true,
    },
    {
      name: 'telefono',
      label: 'Teléfono',
      type: 'phone',
      required: true,
      searchable: true,
    },
    {
      name: 'estado',
      label: 'Estado',
      type: 'enum',
      enumValues: ['prospecto', 'calificado', 'cliente', 'inactivo'],
      required: true,
      filterable: true,
      defaultValue: 'prospecto',
    },
    {
      name: 'cedula',
      label: 'Cédula',
      type: 'string',
      searchable: true,
    },
    {
      name: 'ciudad',
      label: 'Ciudad',
      type: 'string',
      filterable: true,
      sortable: true,
    },
    {
      name: 'pais',
      label: 'País',
      type: 'string',
      filterable: true,
      sortable: true,
    },
    {
      name: 'notas',
      label: 'Notas',
      type: 'textarea',
      searchable: true,
    },
  ],
  defaultSort: {
    field: 'apellidos',
    order: 'asc',
  },
};
